/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.uib.owu.liferay.cas.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import es.uib.owu.liferay.cas.model.CasServiceUtil;
import es.uib.owu.liferay.cas.service.CasServiceUtilLocalServiceUtil;

/**
 * The extended model base implementation for the CasServiceUtil service. Represents a row in the &quot;casutil_CasServiceUtil&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CasServiceUtilImpl}.
 * </p>
 *
 * @author vrf495
 * @see CasServiceUtilImpl
 * @see es.uib.owu.liferay.cas.model.CasServiceUtil
 * @generated
 */
public abstract class CasServiceUtilBaseImpl extends CasServiceUtilModelImpl
	implements CasServiceUtil {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cas service util model instance should use the {@link CasServiceUtil} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			CasServiceUtilLocalServiceUtil.addCasServiceUtil(this);
		}
		else {
			CasServiceUtilLocalServiceUtil.updateCasServiceUtil(this);
		}
	}
}