/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.uib.owu.liferay.cas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CasServiceUtil service. Represents a row in the &quot;casutil_CasServiceUtil&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.uib.owu.liferay.cas.model.impl.CasServiceUtilModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.uib.owu.liferay.cas.model.impl.CasServiceUtilImpl}.
 * </p>
 *
 * @author vrf495
 * @see CasServiceUtil
 * @see es.uib.owu.liferay.cas.model.impl.CasServiceUtilImpl
 * @see es.uib.owu.liferay.cas.model.impl.CasServiceUtilModelImpl
 * @generated
 */
public interface CasServiceUtilModel extends BaseModel<CasServiceUtil>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cas service util model instance should use the {@link CasServiceUtil} interface instead.
	 */

	/**
	 * Returns the primary key of this cas service util.
	 *
	 * @return the primary key of this cas service util
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cas service util.
	 *
	 * @param primaryKey the primary key of this cas service util
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cas service ID of this cas service util.
	 *
	 * @return the cas service ID of this cas service util
	 */
	public long getCasServiceId();

	/**
	 * Sets the cas service ID of this cas service util.
	 *
	 * @param casServiceId the cas service ID of this cas service util
	 */
	public void setCasServiceId(long casServiceId);

	/**
	 * Returns the proxy granting ticket iou of this cas service util.
	 *
	 * @return the proxy granting ticket iou of this cas service util
	 */
	@AutoEscape
	public String getProxyGrantingTicketIou();

	/**
	 * Sets the proxy granting ticket iou of this cas service util.
	 *
	 * @param proxyGrantingTicketIou the proxy granting ticket iou of this cas service util
	 */
	public void setProxyGrantingTicketIou(String proxyGrantingTicketIou);

	/**
	 * Returns the proxy granting ticket of this cas service util.
	 *
	 * @return the proxy granting ticket of this cas service util
	 */
	@AutoEscape
	public String getProxyGrantingTicket();

	/**
	 * Sets the proxy granting ticket of this cas service util.
	 *
	 * @param proxyGrantingTicket the proxy granting ticket of this cas service util
	 */
	public void setProxyGrantingTicket(String proxyGrantingTicket);

	/**
	 * Returns the group ID of this cas service util.
	 *
	 * @return the group ID of this cas service util
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this cas service util.
	 *
	 * @param groupId the group ID of this cas service util
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this cas service util.
	 *
	 * @return the company ID of this cas service util
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cas service util.
	 *
	 * @param companyId the company ID of this cas service util
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this cas service util.
	 *
	 * @return the user ID of this cas service util
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this cas service util.
	 *
	 * @param userId the user ID of this cas service util
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cas service util.
	 *
	 * @return the user uuid of this cas service util
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this cas service util.
	 *
	 * @param userUuid the user uuid of this cas service util
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cas service util.
	 *
	 * @return the user name of this cas service util
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this cas service util.
	 *
	 * @param userName the user name of this cas service util
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this cas service util.
	 *
	 * @return the create date of this cas service util
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cas service util.
	 *
	 * @param createDate the create date of this cas service util
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cas service util.
	 *
	 * @return the modified date of this cas service util
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cas service util.
	 *
	 * @param modifiedDate the modified date of this cas service util
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.uib.owu.liferay.cas.model.CasServiceUtil casServiceUtil);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.uib.owu.liferay.cas.model.CasServiceUtil> toCacheModel();

	@Override
	public es.uib.owu.liferay.cas.model.CasServiceUtil toEscapedModel();

	@Override
	public es.uib.owu.liferay.cas.model.CasServiceUtil toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}